server:
  port: 8023

spring:
  application:
    # 应用名称（nacos)
    name: product-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
